### ISSUE TITLE
Retain Collections more options(3 dots) icon when more options dropdown in open

### ISSUE THREAD

**Issue by MrRobz** [MrRobz/icon-shelf#17]
## Expected Behavior
While more options dropdown menu is open and moving mouse around, the 3 dots icon should remain visible.

## Current Behavior

https://user-images.githubusercontent.com/21201812/136711046-c4022d6d-e8df-416f-a163-5330a92dac7b.mp4

**Comment by Vanfarock** [comment]
Hi @MrRobz, I'd like to work in this issue. Could you assign it to me?
